[package]
name = "Ingress-Engine"
version = "0.1.0"
edition = "2021"
[dependencies]
bytes = "1.11.0"
env_logger = "0.11.8"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.49.0", features = ["full"] }
toml = "0.9.11"
